### PR TITLE
Ship system assignment

### LINKED ISSUE #249: Ship Systems - Define the backend API for assigning ship system definitions to ship plugins

### LINKED ISSUE #252: Ship Systems - Create the UI for Assigning a ship system definition to a ship plugin.

### PR DESCRIPTION
**Pull request by alexanderson1993**
## Description

Adds the backend and UI for assigning ship systems to ship plugins. 

## Related Issue

Closes #249
Closes #252 

## How do you know the changes work correctly?

Manual Test:
- Make sure you have some Ship Systems defined - they should be present in the default plugin
- Go to the ship plugin editor and choose a ship.
- Go to the systems tab
- Add one of the impulse engine systems to the ship by clicking on it. It should move to the right-side list.
- Click on the impulse engine on the right side to remove it - it should move back to the left list.

## Screenshots (if appropriate):

Screen Shot 2022-04-27 at 8 48 58 PM

## Types of changes

- [ ] Docs Change (changes were only made to documentation)
- [ ] Refactor (non-breaking change which improves code)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
      change)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [x] My code follows the code style of this project.
- [x] My change requires a change to the built-in project documentation.
- [x] My change adds dependencies to this project.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by jnoahjohnson — APPROVED** [review]
I was able to reproduce the new feature and everythign looks good.

There are some TypeScript errors, but I am unsure how you are handling those currently.

**Comment by alexanderson1993** [comment]
@jnoahjohnson What typescript errors did you find? They should have been picked up by the Github Actions checks.

**Comment by jnoahjohnson** [comment]
@alexanderson1993 I actually just opened it back up and it is working just fine. I just barely got the repo up and going so it was probably just something with my setup that was causing VSCode to have issues.

**Comment by alexanderson1993** [comment]
@jnoahjohnson Yeah, I've found that VS Code sometimes gets behind with the gnarly types that Thorium Nova uses. Sometimes you need to open the file that has the type definition so VS Code can pick it up. Or using the `Developer: Reload Window` command usually takes care of it too.

When all else fails, `npm run typecheck`.

Thanks for the review!

**Pull request merged**
