### PR TITLE
Interstellar palette

### LINKED ISSUE #182: Star Map - Create the editor palette for the star map

### LINKED ISSUE #183: Star Map - Support editing solar system properties with the editor palette

### PR DESCRIPTION
**Pull request by alexanderson1993**
## Description

Adds an editor palette for updating the properties of solar systems on the star map.

## Related Issue

Closes #182 
Closes #183 

## How do you know the changes work correctly?

Manual Test:
- Open the starmap editor
- Choose a system (create one if necessary)
- Click on the system
- See the editor.
- Change the name. It should reflect on the star itself.

## Types of changes

- [ ] Docs Change (changes were only made to documentation)
- [ ] Refactor (non-breaking change which improves code)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
      change)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the built-in project documentation.
- [ ] My change adds dependencies to this project.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by astrolamb-gaming** [comment]
When I try to start a flight, I get to the ship name selection screen and am unable to press the "Next" button.

**Comment by alexanderson1993** [comment]
This PR doesn't involve anything related to starting a flight, but I'll take a look and see if I can get that fixed.

**Comment by astrolamb-gaming** [comment]
I was messing around trying to get things working; I think first of all I had not set up git correctly to work with the plugin system we have for thorium. But then I had to step away from my pc for awhile and I haven't had a chance to test again.

**Comment by astrolamb-gaming** [comment]
Alright, got things working. A few things:

- Clicking on a system moves the system so your cursor is directly at the center of the circle representing the system.
- Pressing the "edit" button has no effect that I've noticed.
- If your cursor is within more than one circle, dragging will move all of the associated systems.
- Double clicking opens the system map, which currently contains an immovable cube and euclidean coordinates (this may simply not be implemented yet, I haven't been following development as closely as I'd like to be).
- No where have I found a place to change the name of a system.

**Comment by astrolamb-gaming** [comment]
Things look good - there is one thing though: when you double click a system it takes you to the system map (empty of course). When you press the back button, the starmap goes nuts and the address bar goes back and forth between the system map and star map.

**Comment by alexanderson1993** [comment]
The address bar thing should be fixed in #258

**Pull request merged**
